# My workflow
name: My first workflow

# on:
#   schedule:
#     - cron: '*/15 * * * *'

on: [push, pull_request]
# on:
#   push:
#     branches:
#       - main
#       - release/**
#     pull_request:
#       types: [opend, assigned]

# strategy:
#   matrix:
#     os_version: [macos-latest, ubuntu-latest]
#     node_version: [10, 12, 14]

jobs:
  job_1:
    name: My first job
    runs-on: ubuntu-latest
    # runs-on: ${{matrix.os_version}}
    steps:
      # - uses: actions/setup-node@v2
      # - name: Install Dependecies
      #   run: npm install
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # - name: Clean install dependenceis and build
      #   run: |
      #     npm ci
      #     npm run build
      #   working-directory: ./temp
      #   shell: bash

      - name: call youtube api
        run: python main.py
        env:
          YOUTUBE: ${{ secrets.API_KEY }}
        # with:
        #   node-version: ${{node_version}}
  # job_2:
  #   name: My second job
  #   needs: job_1
  # job_3:
  #   name: My third job
  #   needs: [job_1, job_2]
